---
extends: default

rules:
  line-length:
    max: 150
    level: warning
  truthy:
    check-keys: false
  comments:
    min-spaces-from-content: 1
  indentation:
    spaces: 2
    indent-sequences: consistent
  document-start: disable

ignore:
  - .github/
  - node_modules/
  - "*.json"
